package bookManage.model;

public class BookGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.id
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.bookName
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.inventory
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.price
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.saleprice
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.Author
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_group.Publication_name
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    private String publicationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.id
     *
     * @return the value of book_group.id
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.id
     *
     * @param id the value for book_group.id
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.bookName
     *
     * @return the value of book_group.bookName
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.bookName
     *
     * @param bookname the value for book_group.bookName
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.inventory
     *
     * @return the value of book_group.inventory
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.inventory
     *
     * @param inventory the value for book_group.inventory
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setInventory(String inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.price
     *
     * @return the value of book_group.price
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.price
     *
     * @param price the value for book_group.price
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.saleprice
     *
     * @return the value of book_group.saleprice
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.saleprice
     *
     * @param saleprice the value for book_group.saleprice
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setSaleprice(String saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.Author
     *
     * @return the value of book_group.Author
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.Author
     *
     * @param author the value for book_group.Author
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_group.Publication_name
     *
     * @return the value of book_group.Publication_name
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public String getPublicationName() {
        return publicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_group.Publication_name
     *
     * @param publicationName the value for book_group.Publication_name
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    public void setPublicationName(String publicationName) {
        this.publicationName = publicationName;
    }
}