package bookManage.model;

public class BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.id
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Bcode
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String bcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Cnumber
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Collections
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String collections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.isbn
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.bName
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Subtitle_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String subtitleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Series_title
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String seriesTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Author
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Classify_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String classifyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Classify_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String classifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Publication_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String publicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Publication_place
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String publicationPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Publication_time
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String publicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Page_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String pageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.format
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.price
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.language
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.book_category
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String bookCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.book_layout
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String bookLayout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.edition
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String edition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.Register_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String registerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.annex
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String annex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.notes
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.keywords
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.summary
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.First_fight
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    private String firstFight;

    private String inventory;

    public String getInventory() {
        return inventory;
    }

    public void setInventory(String inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.id
     *
     * @return the value of book_info.id
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.id
     *
     * @param id the value for book_info.id
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Bcode
     *
     * @return the value of book_info.Bcode
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getBcode() {
        return bcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Bcode
     *
     * @param bcode the value for book_info.Bcode
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setBcode(String bcode) {
        this.bcode = bcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Cnumber
     *
     * @return the value of book_info.Cnumber
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Cnumber
     *
     * @param cnumber the value for book_info.Cnumber
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setCnumber(String cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Collections
     *
     * @return the value of book_info.Collections
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getCollections() {
        return collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Collections
     *
     * @param collections the value for book_info.Collections
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setCollections(String collections) {
        this.collections = collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.isbn
     *
     * @return the value of book_info.isbn
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.isbn
     *
     * @param isbn the value for book_info.isbn
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.bName
     *
     * @return the value of book_info.bName
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.bName
     *
     * @param bname the value for book_info.bName
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Subtitle_name
     *
     * @return the value of book_info.Subtitle_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getSubtitleName() {
        return subtitleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Subtitle_name
     *
     * @param subtitleName the value for book_info.Subtitle_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setSubtitleName(String subtitleName) {
        this.subtitleName = subtitleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Series_title
     *
     * @return the value of book_info.Series_title
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getSeriesTitle() {
        return seriesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Series_title
     *
     * @param seriesTitle the value for book_info.Series_title
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setSeriesTitle(String seriesTitle) {
        this.seriesTitle = seriesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Author
     *
     * @return the value of book_info.Author
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Author
     *
     * @param author the value for book_info.Author
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Classify_number
     *
     * @return the value of book_info.Classify_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getClassifyNumber() {
        return classifyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Classify_number
     *
     * @param classifyNumber the value for book_info.Classify_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setClassifyNumber(String classifyNumber) {
        this.classifyNumber = classifyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Classify_name
     *
     * @return the value of book_info.Classify_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Classify_name
     *
     * @param classifyName the value for book_info.Classify_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Publication_name
     *
     * @return the value of book_info.Publication_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getPublicationName() {
        return publicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Publication_name
     *
     * @param publicationName the value for book_info.Publication_name
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setPublicationName(String publicationName) {
        this.publicationName = publicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Publication_place
     *
     * @return the value of book_info.Publication_place
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getPublicationPlace() {
        return publicationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Publication_place
     *
     * @param publicationPlace the value for book_info.Publication_place
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setPublicationPlace(String publicationPlace) {
        this.publicationPlace = publicationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Publication_time
     *
     * @return the value of book_info.Publication_time
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getPublicationTime() {
        return publicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Publication_time
     *
     * @param publicationTime the value for book_info.Publication_time
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setPublicationTime(String publicationTime) {
        this.publicationTime = publicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Page_number
     *
     * @return the value of book_info.Page_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getPageNumber() {
        return pageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Page_number
     *
     * @param pageNumber the value for book_info.Page_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setPageNumber(String pageNumber) {
        this.pageNumber = pageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.format
     *
     * @return the value of book_info.format
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.format
     *
     * @param format the value for book_info.format
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.price
     *
     * @return the value of book_info.price
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.price
     *
     * @param price the value for book_info.price
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.language
     *
     * @return the value of book_info.language
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.language
     *
     * @param language the value for book_info.language
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.book_category
     *
     * @return the value of book_info.book_category
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getBookCategory() {
        return bookCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.book_category
     *
     * @param bookCategory the value for book_info.book_category
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.book_layout
     *
     * @return the value of book_info.book_layout
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getBookLayout() {
        return bookLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.book_layout
     *
     * @param bookLayout the value for book_info.book_layout
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setBookLayout(String bookLayout) {
        this.bookLayout = bookLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.edition
     *
     * @return the value of book_info.edition
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.edition
     *
     * @param edition the value for book_info.edition
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setEdition(String edition) {
        this.edition = edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.Register_number
     *
     * @return the value of book_info.Register_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.Register_number
     *
     * @param registerNumber the value for book_info.Register_number
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setRegisterNumber(String registerNumber) {
        this.registerNumber = registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.annex
     *
     * @return the value of book_info.annex
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getAnnex() {
        return annex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.annex
     *
     * @param annex the value for book_info.annex
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setAnnex(String annex) {
        this.annex = annex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.notes
     *
     * @return the value of book_info.notes
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.notes
     *
     * @param notes the value for book_info.notes
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.keywords
     *
     * @return the value of book_info.keywords
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.keywords
     *
     * @param keywords the value for book_info.keywords
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.summary
     *
     * @return the value of book_info.summary
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.summary
     *
     * @param summary the value for book_info.summary
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.First_fight
     *
     * @return the value of book_info.First_fight
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getFirstFight() {
        return firstFight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.First_fight
     *
     * @param firstFight the value for book_info.First_fight
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setFirstFight(String firstFight) {
        this.firstFight = firstFight;
    }
}