package bookManage.model;

import java.util.ArrayList;
import java.util.List;

public class BookInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public BookInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBcodeIsNull() {
            addCriterion("Bcode is null");
            return (Criteria) this;
        }

        public Criteria andBcodeIsNotNull() {
            addCriterion("Bcode is not null");
            return (Criteria) this;
        }

        public Criteria andBcodeEqualTo(String value) {
            addCriterion("Bcode =", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeNotEqualTo(String value) {
            addCriterion("Bcode <>", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeGreaterThan(String value) {
            addCriterion("Bcode >", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeGreaterThanOrEqualTo(String value) {
            addCriterion("Bcode >=", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeLessThan(String value) {
            addCriterion("Bcode <", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeLessThanOrEqualTo(String value) {
            addCriterion("Bcode <=", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeLike(String value) {
            addCriterion("Bcode like", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeNotLike(String value) {
            addCriterion("Bcode not like", value, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeIn(List<String> values) {
            addCriterion("Bcode in", values, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeNotIn(List<String> values) {
            addCriterion("Bcode not in", values, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeBetween(String value1, String value2) {
            addCriterion("Bcode between", value1, value2, "bcode");
            return (Criteria) this;
        }

        public Criteria andBcodeNotBetween(String value1, String value2) {
            addCriterion("Bcode not between", value1, value2, "bcode");
            return (Criteria) this;
        }

        public Criteria andCnumberIsNull() {
            addCriterion("Cnumber is null");
            return (Criteria) this;
        }

        public Criteria andCnumberIsNotNull() {
            addCriterion("Cnumber is not null");
            return (Criteria) this;
        }

        public Criteria andCnumberEqualTo(String value) {
            addCriterion("Cnumber =", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberNotEqualTo(String value) {
            addCriterion("Cnumber <>", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberGreaterThan(String value) {
            addCriterion("Cnumber >", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberGreaterThanOrEqualTo(String value) {
            addCriterion("Cnumber >=", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberLessThan(String value) {
            addCriterion("Cnumber <", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberLessThanOrEqualTo(String value) {
            addCriterion("Cnumber <=", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberLike(String value) {
            addCriterion("Cnumber like", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberNotLike(String value) {
            addCriterion("Cnumber not like", value, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberIn(List<String> values) {
            addCriterion("Cnumber in", values, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberNotIn(List<String> values) {
            addCriterion("Cnumber not in", values, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberBetween(String value1, String value2) {
            addCriterion("Cnumber between", value1, value2, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCnumberNotBetween(String value1, String value2) {
            addCriterion("Cnumber not between", value1, value2, "cnumber");
            return (Criteria) this;
        }

        public Criteria andCollectionsIsNull() {
            addCriterion("Collections is null");
            return (Criteria) this;
        }

        public Criteria andCollectionsIsNotNull() {
            addCriterion("Collections is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionsEqualTo(String value) {
            addCriterion("Collections =", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsNotEqualTo(String value) {
            addCriterion("Collections <>", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsGreaterThan(String value) {
            addCriterion("Collections >", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsGreaterThanOrEqualTo(String value) {
            addCriterion("Collections >=", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsLessThan(String value) {
            addCriterion("Collections <", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsLessThanOrEqualTo(String value) {
            addCriterion("Collections <=", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsLike(String value) {
            addCriterion("Collections like", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsNotLike(String value) {
            addCriterion("Collections not like", value, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsIn(List<String> values) {
            addCriterion("Collections in", values, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsNotIn(List<String> values) {
            addCriterion("Collections not in", values, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsBetween(String value1, String value2) {
            addCriterion("Collections between", value1, value2, "collections");
            return (Criteria) this;
        }

        public Criteria andCollectionsNotBetween(String value1, String value2) {
            addCriterion("Collections not between", value1, value2, "collections");
            return (Criteria) this;
        }

        public Criteria andIsbnIsNull() {
            addCriterion("isbn is null");
            return (Criteria) this;
        }

        public Criteria andIsbnIsNotNull() {
            addCriterion("isbn is not null");
            return (Criteria) this;
        }

        public Criteria andIsbnEqualTo(String value) {
            addCriterion("isbn =", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotEqualTo(String value) {
            addCriterion("isbn <>", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThan(String value) {
            addCriterion("isbn >", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("isbn >=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThan(String value) {
            addCriterion("isbn <", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThanOrEqualTo(String value) {
            addCriterion("isbn <=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLike(String value) {
            addCriterion("isbn like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotLike(String value) {
            addCriterion("isbn not like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnIn(List<String> values) {
            addCriterion("isbn in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotIn(List<String> values) {
            addCriterion("isbn not in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnBetween(String value1, String value2) {
            addCriterion("isbn between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotBetween(String value1, String value2) {
            addCriterion("isbn not between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andBnameIsNull() {
            addCriterion("bName is null");
            return (Criteria) this;
        }

        public Criteria andBnameIsNotNull() {
            addCriterion("bName is not null");
            return (Criteria) this;
        }

        public Criteria andBnameEqualTo(String value) {
            addCriterion("bName =", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotEqualTo(String value) {
            addCriterion("bName <>", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameGreaterThan(String value) {
            addCriterion("bName >", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameGreaterThanOrEqualTo(String value) {
            addCriterion("bName >=", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLessThan(String value) {
            addCriterion("bName <", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLessThanOrEqualTo(String value) {
            addCriterion("bName <=", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLike(String value) {
            addCriterion("bName like", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotLike(String value) {
            addCriterion("bName not like", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameIn(List<String> values) {
            addCriterion("bName in", values, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotIn(List<String> values) {
            addCriterion("bName not in", values, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameBetween(String value1, String value2) {
            addCriterion("bName between", value1, value2, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotBetween(String value1, String value2) {
            addCriterion("bName not between", value1, value2, "bname");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameIsNull() {
            addCriterion("Subtitle_name is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameIsNotNull() {
            addCriterion("Subtitle_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameEqualTo(String value) {
            addCriterion("Subtitle_name =", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameNotEqualTo(String value) {
            addCriterion("Subtitle_name <>", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameGreaterThan(String value) {
            addCriterion("Subtitle_name >", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameGreaterThanOrEqualTo(String value) {
            addCriterion("Subtitle_name >=", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameLessThan(String value) {
            addCriterion("Subtitle_name <", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameLessThanOrEqualTo(String value) {
            addCriterion("Subtitle_name <=", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameLike(String value) {
            addCriterion("Subtitle_name like", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameNotLike(String value) {
            addCriterion("Subtitle_name not like", value, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameIn(List<String> values) {
            addCriterion("Subtitle_name in", values, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameNotIn(List<String> values) {
            addCriterion("Subtitle_name not in", values, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameBetween(String value1, String value2) {
            addCriterion("Subtitle_name between", value1, value2, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSubtitleNameNotBetween(String value1, String value2) {
            addCriterion("Subtitle_name not between", value1, value2, "subtitleName");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleIsNull() {
            addCriterion("Series_title is null");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleIsNotNull() {
            addCriterion("Series_title is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleEqualTo(String value) {
            addCriterion("Series_title =", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleNotEqualTo(String value) {
            addCriterion("Series_title <>", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleGreaterThan(String value) {
            addCriterion("Series_title >", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Series_title >=", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleLessThan(String value) {
            addCriterion("Series_title <", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleLessThanOrEqualTo(String value) {
            addCriterion("Series_title <=", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleLike(String value) {
            addCriterion("Series_title like", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleNotLike(String value) {
            addCriterion("Series_title not like", value, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleIn(List<String> values) {
            addCriterion("Series_title in", values, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleNotIn(List<String> values) {
            addCriterion("Series_title not in", values, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleBetween(String value1, String value2) {
            addCriterion("Series_title between", value1, value2, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andSeriesTitleNotBetween(String value1, String value2) {
            addCriterion("Series_title not between", value1, value2, "seriesTitle");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("Author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("Author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("Author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("Author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("Author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("Author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("Author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("Author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("Author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("Author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("Author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("Author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("Author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("Author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberIsNull() {
            addCriterion("Classify_number is null");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberIsNotNull() {
            addCriterion("Classify_number is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberEqualTo(String value) {
            addCriterion("Classify_number =", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberNotEqualTo(String value) {
            addCriterion("Classify_number <>", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberGreaterThan(String value) {
            addCriterion("Classify_number >", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Classify_number >=", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberLessThan(String value) {
            addCriterion("Classify_number <", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberLessThanOrEqualTo(String value) {
            addCriterion("Classify_number <=", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberLike(String value) {
            addCriterion("Classify_number like", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberNotLike(String value) {
            addCriterion("Classify_number not like", value, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberIn(List<String> values) {
            addCriterion("Classify_number in", values, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberNotIn(List<String> values) {
            addCriterion("Classify_number not in", values, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberBetween(String value1, String value2) {
            addCriterion("Classify_number between", value1, value2, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNumberNotBetween(String value1, String value2) {
            addCriterion("Classify_number not between", value1, value2, "classifyNumber");
            return (Criteria) this;
        }

        public Criteria andClassifyNameIsNull() {
            addCriterion("Classify_name is null");
            return (Criteria) this;
        }

        public Criteria andClassifyNameIsNotNull() {
            addCriterion("Classify_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyNameEqualTo(String value) {
            addCriterion("Classify_name =", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameNotEqualTo(String value) {
            addCriterion("Classify_name <>", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameGreaterThan(String value) {
            addCriterion("Classify_name >", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameGreaterThanOrEqualTo(String value) {
            addCriterion("Classify_name >=", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameLessThan(String value) {
            addCriterion("Classify_name <", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameLessThanOrEqualTo(String value) {
            addCriterion("Classify_name <=", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameLike(String value) {
            addCriterion("Classify_name like", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameNotLike(String value) {
            addCriterion("Classify_name not like", value, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameIn(List<String> values) {
            addCriterion("Classify_name in", values, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameNotIn(List<String> values) {
            addCriterion("Classify_name not in", values, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameBetween(String value1, String value2) {
            addCriterion("Classify_name between", value1, value2, "classifyName");
            return (Criteria) this;
        }

        public Criteria andClassifyNameNotBetween(String value1, String value2) {
            addCriterion("Classify_name not between", value1, value2, "classifyName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameIsNull() {
            addCriterion("Publication_name is null");
            return (Criteria) this;
        }

        public Criteria andPublicationNameIsNotNull() {
            addCriterion("Publication_name is not null");
            return (Criteria) this;
        }

        public Criteria andPublicationNameEqualTo(String value) {
            addCriterion("Publication_name =", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameNotEqualTo(String value) {
            addCriterion("Publication_name <>", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameGreaterThan(String value) {
            addCriterion("Publication_name >", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameGreaterThanOrEqualTo(String value) {
            addCriterion("Publication_name >=", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameLessThan(String value) {
            addCriterion("Publication_name <", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameLessThanOrEqualTo(String value) {
            addCriterion("Publication_name <=", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameLike(String value) {
            addCriterion("Publication_name like", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameNotLike(String value) {
            addCriterion("Publication_name not like", value, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameIn(List<String> values) {
            addCriterion("Publication_name in", values, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameNotIn(List<String> values) {
            addCriterion("Publication_name not in", values, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameBetween(String value1, String value2) {
            addCriterion("Publication_name between", value1, value2, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationNameNotBetween(String value1, String value2) {
            addCriterion("Publication_name not between", value1, value2, "publicationName");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceIsNull() {
            addCriterion("Publication_place is null");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceIsNotNull() {
            addCriterion("Publication_place is not null");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceEqualTo(String value) {
            addCriterion("Publication_place =", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceNotEqualTo(String value) {
            addCriterion("Publication_place <>", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceGreaterThan(String value) {
            addCriterion("Publication_place >", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("Publication_place >=", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceLessThan(String value) {
            addCriterion("Publication_place <", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceLessThanOrEqualTo(String value) {
            addCriterion("Publication_place <=", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceLike(String value) {
            addCriterion("Publication_place like", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceNotLike(String value) {
            addCriterion("Publication_place not like", value, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceIn(List<String> values) {
            addCriterion("Publication_place in", values, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceNotIn(List<String> values) {
            addCriterion("Publication_place not in", values, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceBetween(String value1, String value2) {
            addCriterion("Publication_place between", value1, value2, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationPlaceNotBetween(String value1, String value2) {
            addCriterion("Publication_place not between", value1, value2, "publicationPlace");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeIsNull() {
            addCriterion("Publication_time is null");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeIsNotNull() {
            addCriterion("Publication_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeEqualTo(String value) {
            addCriterion("Publication_time =", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeNotEqualTo(String value) {
            addCriterion("Publication_time <>", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeGreaterThan(String value) {
            addCriterion("Publication_time >", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Publication_time >=", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeLessThan(String value) {
            addCriterion("Publication_time <", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeLessThanOrEqualTo(String value) {
            addCriterion("Publication_time <=", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeLike(String value) {
            addCriterion("Publication_time like", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeNotLike(String value) {
            addCriterion("Publication_time not like", value, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeIn(List<String> values) {
            addCriterion("Publication_time in", values, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeNotIn(List<String> values) {
            addCriterion("Publication_time not in", values, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeBetween(String value1, String value2) {
            addCriterion("Publication_time between", value1, value2, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPublicationTimeNotBetween(String value1, String value2) {
            addCriterion("Publication_time not between", value1, value2, "publicationTime");
            return (Criteria) this;
        }

        public Criteria andPageNumberIsNull() {
            addCriterion("Page_number is null");
            return (Criteria) this;
        }

        public Criteria andPageNumberIsNotNull() {
            addCriterion("Page_number is not null");
            return (Criteria) this;
        }

        public Criteria andPageNumberEqualTo(String value) {
            addCriterion("Page_number =", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberNotEqualTo(String value) {
            addCriterion("Page_number <>", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberGreaterThan(String value) {
            addCriterion("Page_number >", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Page_number >=", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberLessThan(String value) {
            addCriterion("Page_number <", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberLessThanOrEqualTo(String value) {
            addCriterion("Page_number <=", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberLike(String value) {
            addCriterion("Page_number like", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberNotLike(String value) {
            addCriterion("Page_number not like", value, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberIn(List<String> values) {
            addCriterion("Page_number in", values, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberNotIn(List<String> values) {
            addCriterion("Page_number not in", values, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberBetween(String value1, String value2) {
            addCriterion("Page_number between", value1, value2, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andPageNumberNotBetween(String value1, String value2) {
            addCriterion("Page_number not between", value1, value2, "pageNumber");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andBookCategoryIsNull() {
            addCriterion("book_category is null");
            return (Criteria) this;
        }

        public Criteria andBookCategoryIsNotNull() {
            addCriterion("book_category is not null");
            return (Criteria) this;
        }

        public Criteria andBookCategoryEqualTo(String value) {
            addCriterion("book_category =", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryNotEqualTo(String value) {
            addCriterion("book_category <>", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryGreaterThan(String value) {
            addCriterion("book_category >", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("book_category >=", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryLessThan(String value) {
            addCriterion("book_category <", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryLessThanOrEqualTo(String value) {
            addCriterion("book_category <=", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryLike(String value) {
            addCriterion("book_category like", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryNotLike(String value) {
            addCriterion("book_category not like", value, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryIn(List<String> values) {
            addCriterion("book_category in", values, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryNotIn(List<String> values) {
            addCriterion("book_category not in", values, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryBetween(String value1, String value2) {
            addCriterion("book_category between", value1, value2, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookCategoryNotBetween(String value1, String value2) {
            addCriterion("book_category not between", value1, value2, "bookCategory");
            return (Criteria) this;
        }

        public Criteria andBookLayoutIsNull() {
            addCriterion("book_layout is null");
            return (Criteria) this;
        }

        public Criteria andBookLayoutIsNotNull() {
            addCriterion("book_layout is not null");
            return (Criteria) this;
        }

        public Criteria andBookLayoutEqualTo(String value) {
            addCriterion("book_layout =", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutNotEqualTo(String value) {
            addCriterion("book_layout <>", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutGreaterThan(String value) {
            addCriterion("book_layout >", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutGreaterThanOrEqualTo(String value) {
            addCriterion("book_layout >=", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutLessThan(String value) {
            addCriterion("book_layout <", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutLessThanOrEqualTo(String value) {
            addCriterion("book_layout <=", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutLike(String value) {
            addCriterion("book_layout like", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutNotLike(String value) {
            addCriterion("book_layout not like", value, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutIn(List<String> values) {
            addCriterion("book_layout in", values, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutNotIn(List<String> values) {
            addCriterion("book_layout not in", values, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutBetween(String value1, String value2) {
            addCriterion("book_layout between", value1, value2, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andBookLayoutNotBetween(String value1, String value2) {
            addCriterion("book_layout not between", value1, value2, "bookLayout");
            return (Criteria) this;
        }

        public Criteria andEditionIsNull() {
            addCriterion("edition is null");
            return (Criteria) this;
        }

        public Criteria andEditionIsNotNull() {
            addCriterion("edition is not null");
            return (Criteria) this;
        }

        public Criteria andEditionEqualTo(String value) {
            addCriterion("edition =", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotEqualTo(String value) {
            addCriterion("edition <>", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionGreaterThan(String value) {
            addCriterion("edition >", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionGreaterThanOrEqualTo(String value) {
            addCriterion("edition >=", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLessThan(String value) {
            addCriterion("edition <", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLessThanOrEqualTo(String value) {
            addCriterion("edition <=", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLike(String value) {
            addCriterion("edition like", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotLike(String value) {
            addCriterion("edition not like", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionIn(List<String> values) {
            addCriterion("edition in", values, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotIn(List<String> values) {
            addCriterion("edition not in", values, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionBetween(String value1, String value2) {
            addCriterion("edition between", value1, value2, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotBetween(String value1, String value2) {
            addCriterion("edition not between", value1, value2, "edition");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNull() {
            addCriterion("Register_number is null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNotNull() {
            addCriterion("Register_number is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberEqualTo(String value) {
            addCriterion("Register_number =", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotEqualTo(String value) {
            addCriterion("Register_number <>", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThan(String value) {
            addCriterion("Register_number >", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Register_number >=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThan(String value) {
            addCriterion("Register_number <", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThanOrEqualTo(String value) {
            addCriterion("Register_number <=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLike(String value) {
            addCriterion("Register_number like", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotLike(String value) {
            addCriterion("Register_number not like", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIn(List<String> values) {
            addCriterion("Register_number in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotIn(List<String> values) {
            addCriterion("Register_number not in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberBetween(String value1, String value2) {
            addCriterion("Register_number between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotBetween(String value1, String value2) {
            addCriterion("Register_number not between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andAnnexIsNull() {
            addCriterion("annex is null");
            return (Criteria) this;
        }

        public Criteria andAnnexIsNotNull() {
            addCriterion("annex is not null");
            return (Criteria) this;
        }

        public Criteria andAnnexEqualTo(String value) {
            addCriterion("annex =", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexNotEqualTo(String value) {
            addCriterion("annex <>", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexGreaterThan(String value) {
            addCriterion("annex >", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexGreaterThanOrEqualTo(String value) {
            addCriterion("annex >=", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexLessThan(String value) {
            addCriterion("annex <", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexLessThanOrEqualTo(String value) {
            addCriterion("annex <=", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexLike(String value) {
            addCriterion("annex like", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexNotLike(String value) {
            addCriterion("annex not like", value, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexIn(List<String> values) {
            addCriterion("annex in", values, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexNotIn(List<String> values) {
            addCriterion("annex not in", values, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexBetween(String value1, String value2) {
            addCriterion("annex between", value1, value2, "annex");
            return (Criteria) this;
        }

        public Criteria andAnnexNotBetween(String value1, String value2) {
            addCriterion("annex not between", value1, value2, "annex");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("notes =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("notes <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("notes >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("notes >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("notes <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("notes <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("notes not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andFirstFightIsNull() {
            addCriterion("First_fight is null");
            return (Criteria) this;
        }

        public Criteria andFirstFightIsNotNull() {
            addCriterion("First_fight is not null");
            return (Criteria) this;
        }

        public Criteria andFirstFightEqualTo(String value) {
            addCriterion("First_fight =", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightNotEqualTo(String value) {
            addCriterion("First_fight <>", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightGreaterThan(String value) {
            addCriterion("First_fight >", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightGreaterThanOrEqualTo(String value) {
            addCriterion("First_fight >=", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightLessThan(String value) {
            addCriterion("First_fight <", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightLessThanOrEqualTo(String value) {
            addCriterion("First_fight <=", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightLike(String value) {
            addCriterion("First_fight like", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightNotLike(String value) {
            addCriterion("First_fight not like", value, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightIn(List<String> values) {
            addCriterion("First_fight in", values, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightNotIn(List<String> values) {
            addCriterion("First_fight not in", values, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightBetween(String value1, String value2) {
            addCriterion("First_fight between", value1, value2, "firstFight");
            return (Criteria) this;
        }

        public Criteria andFirstFightNotBetween(String value1, String value2) {
            addCriterion("First_fight not between", value1, value2, "firstFight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 02 00:13:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}