package bookManage.mapper;

import bookManage.model.BookGroup;
import bookManage.model.BookGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int countByExample(BookGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int deleteByExample(BookGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int insert(BookGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int insertSelective(BookGroup record);

    int insertBookGroupBatch(List<BookGroup > bookGroupList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    List<BookGroup> selectByExample(BookGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    BookGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookGroup record, @Param("example") BookGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int updateByExample(@Param("record") BookGroup record, @Param("example") BookGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int updateByPrimaryKeySelective(BookGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_group
     *
     * @mbggenerated Sat Sep 09 15:41:43 CST 2017
     */
    int updateByPrimaryKey(BookGroup record);
}