package bookManage.mapper;

import bookManage.model.BookInfo;
import bookManage.model.BookInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int countByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int deleteByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int insert(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int insertSelective(BookInfo record);

    int insertBookInfoBatch(List<BookInfo > bookInfoList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    List<BookInfo> selectByExample(BookInfoExample example);

    List<BookInfo> selectByGroup(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    BookInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int updateByExample(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int updateByPrimaryKeySelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Wed Aug 02 00:13:30 CST 2017
     */
    int updateByPrimaryKey(BookInfo record);
}